package penitipanhewann;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
public class Home extends javax.swing.JFrame {
    private Connection con;
    private Statement stat;
    private ResultSet res;
    
    String id_delete;
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        koneksi();
        table();
        
    }
    private void koneksi(){
    try {
        Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://127.0.0.1/penitipan_hewan","root","");
        stat = con.createStatement();
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    }
}
    private void tableCari(){
          DefaultTableModel t= new DefaultTableModel();
    t.addColumn("Id Pemilik");
    t.addColumn("Nama");
    t.addColumn("Hewan");
    t.addColumn("Tgl Penitipan");
    t.addColumn("Tgl Kembali");
    t.addColumn("Jml Hari");
    t.addColumn("Harga");
    t.addColumn("Total");
    jTable1.setModel(t); try{ res=stat.executeQuery("select pemilik_hewan.id_pemilik, pemilik_hewan.nama_pemilik,penitipan.Nama_Hewan,penitipan.Tanggal_penitipan,penitipan.Tanggal_kembali,penitipan.Jumlah_Hari,penitipan.Harga,penitipan.Total from pemilik_hewan INNER JOIN penitipan on pemilik_hewan.id_pemilik = penitipan.ID_Pemilik where penitipan.ID_Pemilik='"+CARI.getText()+"' or pemilik_hewan.nama_pemilik like '%"+CARI.getText()+"%'");
    while (res.next()) {
        t.addRow(new Object[]
        {   res.getString("id_pemilik"),
            res.getString("nama_pemilik"),
            res.getString("Nama_Hewan"),
            res.getString("Tanggal_penitipan"),
            res.getString("Tanggal_kembali"),
            res.getString("Jumlah_Hari"),
            res.getString("Harga"),
            res.getString("Total")
        });
    } }
    catch (
    Exception e) {
    JOptionPane.showMessageDialog(rootPane, e);
    }
    }
    private void table(){
      DefaultTableModel t= new DefaultTableModel();
    t.addColumn("Id Pemilik");
    t.addColumn("Nama");
    t.addColumn("Hewan");
    t.addColumn("Tgl Penitipan");
    t.addColumn("Tgl Kembali");
    t.addColumn("Jml Hari");
    t.addColumn("Harga");
    t.addColumn("Total");
    jTable1.setModel(t); try{ res=stat.executeQuery("select pemilik_hewan.id_pemilik, pemilik_hewan.nama_pemilik,penitipan.Nama_Hewan,penitipan.Tanggal_penitipan,penitipan.Tanggal_kembali,penitipan.Jumlah_Hari,penitipan.Harga,penitipan.Total from pemilik_hewan INNER JOIN penitipan on pemilik_hewan.id_pemilik = penitipan.ID_Pemilik");
    while (res.next()) {
        t.addRow(new Object[]
        {   res.getString("id_pemilik"),
            res.getString("nama_pemilik"),
            res.getString("Nama_Hewan"),
            res.getString("Tanggal_penitipan"),
            res.getString("Tanggal_kembali"),
            res.getString("Jumlah_Hari"),
            res.getString("Harga"),
            res.getString("Total")
        });
    } }
    catch (
    Exception e) {
    JOptionPane.showMessageDialog(rootPane, e);
    }
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        userNama = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        CARI = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 255, 102));
        jPanel1.setLayout(null);

        jButton2.setText("Penitipan Baru");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(20, 120, 170, 30);

        userNama.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        userNama.setText("Admin");
        jPanel1.add(userNama);
        userNama.setBounds(490, 10, 80, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Hallo,");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(410, 10, 80, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("informasi Penitipan hewan");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(400, 50, 340, 17);

        jLabel7.setIcon(new javax.swing.ImageIcon("E:\\MATERI KULIAH SEMESTER 5\\pemrograman 2\\PenitipanHewann\\img\\home.jpg")); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 10, 70, 50);

        jButton3.setText("Logout");
        jPanel1.add(jButton3);
        jButton3.setBounds(20, 280, 90, 30);

        jButton4.setText("Daftar Pemilik");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(20, 180, 170, 30);

        jButton5.setText("Cetak Laporan");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(20, 230, 170, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(210, 120, 710, 350);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Cari ID/Nama");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(590, 80, 110, 15);

        CARI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CARIActionPerformed(evt);
            }
        });
        jPanel1.add(CARI);
        CARI.setBounds(710, 70, 110, 30);

        jButton6.setText("Cari");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(830, 70, 60, 30);

        jButton7.setText("Refresh");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(773, 483, 100, 30);

        jButton8.setText("Delete");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(653, 483, 80, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 936, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Pemilik pm = new Pemilik();
        pm.setVisible(true);
        pm.pack();
        pm.setLocationRelativeTo(null);
        pm.setDefaultCloseOperation(WIDTH);
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        DaftarPemiliki dp = new DaftarPemiliki();
        dp.setVisible(true);
        dp.pack();
        dp.setDefaultCloseOperation(WIDTH);
        dp.setLocationRelativeTo(null);
        setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void CARIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CARIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CARIActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        tableCari();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        table();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int i = jTable1.getSelectedRow();
        if(i==-1){
            return;
        }
        String code = (String)jTable1.getValueAt(i,0);
        id_delete = code;
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        int ok=JOptionPane.showConfirmDialog(null,"Apakah Yakin Mendelete record ini???",
        "Confirmation",JOptionPane.YES_NO_CANCEL_OPTION);
        if (ok==0){
            try
            {
                String sql="delete from penitipan where ID_Pemilik='"+id_delete+"'";
                String sql2="delete from pemilik_hewan where id_pemilik='"+id_delete+"'";
                PreparedStatement st=con.prepareStatement(sql);
                PreparedStatement st2=con.prepareStatement(sql2);
                st.executeUpdate();
                st2.executeUpdate();
                JOptionPane.showMessageDialog(null, "Delete Data Sukses");
            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(null, "Delete Data Gagal"+e);
            }
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        CetakLaporan cp = new CetakLaporan();
        cp.setVisible(true);
        cp.pack();
        cp.setDefaultCloseOperation(WIDTH);
        cp.setLocationRelativeTo(null);
        setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CARI;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel userNama;
    // End of variables declaration//GEN-END:variables
}
